package model;
// Generated 15 ene 2025, 9:52:52 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Reuniones generated by hbm2java
 */
public class Reuniones implements java.io.Serializable {

    private static final long serialVersionUID = -5112722321784874797L;
    private Integer idReunion;
    private Users usersByProfesorId;
    private Users usersByAlumnoId;
    private String estado;
    private String estadoEus;
    private String idCentro;
    private String titulo;
    private String asunto;
    private String aula;
    private Timestamp fecha;
    private String dia;
    private char hora;

    public Reuniones() {
    }

    public Reuniones(Users usersByProfesorId, Users usersByAlumnoId, String dia, char hora) {
        this.usersByProfesorId = usersByProfesorId;
        this.usersByAlumnoId = usersByAlumnoId;
        this.dia = dia;
        this.hora = hora;
    }

    public Reuniones(Users usersByProfesorId, Users usersByAlumnoId, String estado, String estadoEus, String idCentro,
                     String titulo, String asunto, String aula, Timestamp fecha, String dia, char hora) {
        this.usersByProfesorId = usersByProfesorId;
        this.usersByAlumnoId = usersByAlumnoId;
        this.estado = estado;
        this.estadoEus = estadoEus;
        this.idCentro = idCentro;
        this.titulo = titulo;
        this.asunto = asunto;
        this.aula = aula;
        this.fecha = fecha;
        this.dia = dia;
        this.hora = hora;
    }

    public Integer getIdReunion() {
        return this.idReunion;
    }

    public void setIdReunion(Integer idReunion) {
        this.idReunion = idReunion;
    }

    public Users getUsersByProfesorId() {
        return this.usersByProfesorId;
    }

    public void setUsersByProfesorId(Users usersByProfesorId) {
        this.usersByProfesorId = usersByProfesorId;
    }

    public Users getUsersByAlumnoId() {
        return this.usersByAlumnoId;
    }

    public void setUsersByAlumnoId(Users usersByAlumnoId) {
        this.usersByAlumnoId = usersByAlumnoId;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getEstadoEus() {
        return this.estadoEus;
    }

    public void setEstadoEus(String estadoEus) {
        this.estadoEus = estadoEus;
    }

    public String getIdCentro() {
        return this.idCentro;
    }

    public void setIdCentro(String idCentro) {
        this.idCentro = idCentro;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getAsunto() {
        return this.asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    public String getAula() {
        return this.aula;
    }

    public void setAula(String aula) {
        this.aula = aula;
    }

    public Timestamp getFecha() {
        return this.fecha;
    }

    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }

    public String getDia() {
        return this.dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    public char getHora() {
        return this.hora;
    }

    public void setHora(char hora) {
        this.hora = hora;
    }

}
